version: '3'
services:
  postgresql:
    image: postgres
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_PASSWORD: admin123
      POSTGRES_USER: postgres
      POSTGRES_DB: microservices
    ports:
      - 5432:5432
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: microservices
      MONGO_INITDB_ROOT_USERNAME: monogoes
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongodb
    ports:
      - 8086:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: monogoes
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_URL: 'mongodb://monogoes:admin123@mongodb:27017/admin'
  service-registry:
    image: harshilpadasala/service-registry
    container_name: service-registry
    ports:
      - 8761:8761
  config-server:
    image: harshilpadasala/config-server
    container_name: config-server
    ports:
      - 8085:8085
    depends_on:
      - service-registry
  api-gateway:
    image: harshilpadasala/api-gateway
    container_name: api-gateway
    depends_on:
      - service-registry
    ports:
      - 8084:8084
  hotel-service:
    image: harshilpadasala/hotel-service
    restart: always
    depends_on: 
      - postgresql
      - service-registry
      - api-gateway
    ports:
      - 8082:8082
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATABASE_URL: jdbc:postgresql//postgresql:5432/microservices?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin123 
  rating-service:
    image: harshilpadasala/rating-service
    ports:
      - 8083:8083
    restart: always
    depends_on:
      - mongodb
      - service-registry
      - api-gateway
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_APPLICATION_JSON: '{
          "spring.data.mongodb.uri" : "mongodb://monogoes:admin123@mongodb:27017/microservices?authSource=admin"
        }'
  user-service:
    image: harshilpadasala/user-service
    ports:
      - 8081:8081
    restart: always
    depends_on:
      - postgresql
      - service-registry
      - config-server
      - api-gateway
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATABASE_URL: jdbc:postgresql//postgresql:5432/microservices?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin123 